apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webpage
  labels:
    app: my-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webpage
  template:
    metadata:
      labels:
        app: my-webpage
    spec:
      containers:
        - name: my-webpage
          image: harbor.rmsd.cloud/my-project/my-webpage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor-registry-secret

