apiVersion: v1
kind: Service
metadata:
  name: my-webpage
spec:
  type: NodePort
  selector:
    app: my-webpage
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # or omit to auto-assign
